name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag laraka/srt-advanced-server:latest
    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: laraka/srt-advanced-server
        tags: latest
        registry: registry.hub.docker.com
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
